version: 2.1
jobs:
  kubeval:
    docker:
      - image: stefanprodan/hrval:v3.1.0
    steps:
      - checkout
      - run:
          name: Validate manifests
          command: |
            kubeval --strict --ignore-missing-schemas -d appmesh-system,kube-system
      - run:
          name: Validate helm releases
          command: |
            hrval appmesh-system/flagger.yaml false master v3
            hrval kube-system/ false master v3

workflows:
  version: 2
  validate:
    jobs:
      - kubeval:
          filters:
            branches:
              ignore:
                - gh-pages
